In [2]:
import cv2
import numpy as np

In [5]:
img = cv2.imread('./OpenCV_Python/data/lena.jpg')

print('img.ndim = ', img.ndim)
print('img.shape = ', img.shape)
print('img.dtype = ', img.dtype)

img = img.astype(np.int32)
print('img.dtype = ', img.dtype)

img = np.uint8(img)
print('img.dtype= ',img.dtype)

img.ndim =  3
img.shape =  (512, 512, 3)
img.dtype =  uint8
img.dtype =  int32
img.dtype=  uint8


In [7]:
# 0403.py
import cv2
##import numpy as np

img = cv2.imread('./OpenCV_Python/data/lena.jpg', cv2.IMREAD_GRAYSCALE)
img[100, 200] = 0  # 화소값(밝기,그레이스케일) 변경
print(img[100:110, 200:210]) # ROI 접근

##for y in range(100, 400):
##    for x in range(200, 300):
##        img[y, x] = 0

img[100:400, 200:300] = 0    # ROI 접근

cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()


[[  0 143 145 132 147 144 142 139 132 138]
 [138 138 143 151 137 144 139 139 138 138]
 [132 139 153 140 133 136 143 138 137 128]
 [137 146 138 125 132 145 139 142 130 128]
 [149 139 130 137 140 145 136 133 132 141]
 [141 139 134 149 149 137 132 127 140 140]
 [142 148 139 142 144 138 146 135 131 130]
 [151 146 136 131 142 144 149 135 126 132]
 [147 131 135 138 147 139 128 125 134 138]
 [135 132 149 142 134 128 122 135 138 129]]


In [9]:
img = cv2.imread('./OpenCV_Python/data/lena.jpg') # cv2.IMREAD_COLOR
img[100, 200] = [255, 0, 0]  # 컬러(BGR) 변경
print(img[100, 200:210]) # ROI 접근

##for y in range(100, 400):
##    for x in range(200, 300):
##        img[y, x] = [255, 0, 0]    # 파랑색(blue)으로 변경

img[100:400, 200:300] = [255, 0, 0]  # ROI 접근
    
cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()


[[255   0   0]
 [116 115 207]
 [120 116 211]
 [107 103 198]
 [119 121 209]
 [116 118 206]
 [115 114 206]
 [112 111 203]
 [104 105 195]
 [110 112 200]]


In [10]:
# 0405.py
import cv2
##import numpy as np

img = cv2.imread('./OpenCV_Python/data/lena.jpg') # cv2.IMREAD_COLOR

##for y in range(100, 400):
##    for x in range(200, 300):
##        img[y, x, 0] = 255      # B-채널을 255로 변경
        
img[100:400, 200:300, 0] = 255  # B-채널을 255로 변경
img[100:400, 300:400, 1] = 255  # G-채널을 255로 변경
img[100:400, 400:500, 2] = 255  # R-채널을 255로 변경

cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()


In [19]:
# 0406.py
import cv2
import numpy as np

src = cv2.imread('./OpenCV_Python/data/lena.jpg', cv2.IMREAD_GRAYSCALE)
dst = np.zeros(src.shape, dtype=src.dtype)

N = 512 # 8, 32, 64
height, width = src.shape    # 그레이스케일 영상
##height, width,_ = src.shape # 컬러영상

h = height // N
w = width  // N
for i in range(N):
    for j in range(N):
        y = i*h
        x = j*w       
        roi = src[y:y+h, x:x+w]
        dst[y:y+h, x:x+w] = cv2.mean(roi)[0]   # 그레이스케일 영상
##        dst[y:y+h, x:x+w] = cv2.mean(roi)[0:3] # 컬러영상
        
cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()


In [23]:
# 0407.py
import cv2
 
src = cv2.imread('./OpenCV_Python/data/lena.jpg', cv2.IMREAD_GRAYSCALE)
roi = cv2.selectROI(src)
print('roi =', roi)

img = src[roi[1]:roi[1]+roi[3],
               roi[0]:roi[0]+roi[2]]

cv2.imshow('Img', img)
cv2.waitKey()
cv2.destroyAllWindows()
#roi selector

roi = (155, 233, 297, 187)


In [27]:
src = cv2.imread('./OpenCV_Python/data/lena.jpg', cv2.IMREAD_GRAYSCALE)
rects = cv2.selectROIs('src', src, False, True)
print('rects =', rects)

for r in rects:
    cv2.rectangle(src, (r[0], r[1]), (r[0]+r[2], r[1]+r[3]), 255)    
##    img = src[r[1]:r[1]+r[3], r[0]:r[0]+r[2]]
##    cv2.imshow('Img', img)
##    cv2.waitKey()

cv2.imshow('src', src)
cv2.waitKey()    
cv2.destroyAllWindows()


#space와 enter로 다중 ROI Selector 만들기

rects = ()


In [29]:
src = cv2.imread('./OpenCV_Python/data/lena.jpg', cv2.IMREAD_GRAYSCALE)

##dst = src          #참조
dst = src.copy()     #복사 
dst[100:400, 200:300] = 0

cv2.imshow('src', src)
cv2.imshow('dst', dst)
cv2.waitKey()    
cv2.destroyAllWindows()

#원본 + ROI체크된 복사본 만들기

In [31]:
src = cv2.imread('./OpenCV_Python/data/lena.jpg', cv2.IMREAD_GRAYSCALE)
shape = src.shape[0], src.shape[1], 3
dst = np.zeros(shape, dtype=np.uint8)

dst[:,:,0] = src      # B-채널 
##dst[:,:,1] = src    # G-채널 
##dst[:,:,2] = src    # R-채널 

dst[100:400, 200:300, :] = [255, 255, 255]

cv2.imshow('src', src)
cv2.imshow('dst', dst)
cv2.waitKey()    
cv2.destroyAllWindows()


In [32]:
src = cv2.imread('./OpenCV_Python/data/lena.jpg')

dst = cv2.split(src) 
print(type(dst))
print(type(dst[0])) # type(dst[1]), type(dst[2])

cv2.imshow('blue',  dst[0])
cv2.imshow('green', dst[1])
cv2.imshow('red',   dst[2])
cv2.waitKey()    
cv2.destroyAllWindows()


<class 'list'>
<class 'numpy.ndarray'>


In [35]:
src = cv2.imread('./OpenCV_Python/data/lena.jpg')

b, g, r = cv2.split(src)
dst = cv2.merge([b, g, r]) # cv2.merge([r, g, b])

print(type(dst))
print(dst.shape)
cv2.imshow('dst',  dst)
cv2.waitKey()    
cv2.destroyAllWindows()


<class 'numpy.ndarray'>
(512, 512, 3)


In [36]:
src = cv2.imread('./OpenCV_Python/data/lena.jpg')

gray   = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
yCrCv = cv2.cvtColor(src, cv2.COLOR_BGR2YCrCb)
hsv    = cv2.cvtColor(src, cv2.COLOR_BGR2HSV)

cv2.imshow('gray',  gray)
cv2.imshow('yCrCv', yCrCv)
cv2.imshow('hsv',   hsv)

cv2.waitKey()    
cv2.destroyAllWindows()


In [37]:
import cv2
import numpy as np
src = cv2.imread('./OpenCV_Python/data/lena.jpg', cv2.IMREAD_GRAYSCALE)

dst = cv2.resize(src, dsize=(320, 240))
dst2 = cv2.resize(src, dsize=(0,0), fx=1.5, fy=1.2)

cv2.imshow('dst', dst)
cv2.imshow('dst2', dst2)
cv2.waitKey()    
cv2.destroyAllWindows()

In [39]:
src = cv2.imread('./OpenCV_Python/data/lena.jpg')

dst1 = cv2.rotate(src, cv2.ROTATE_90_CLOCKWISE)
dst2 = cv2.rotate(src, cv2.ROTATE_90_COUNTERCLOCKWISE)

cv2.imshow('dst1',  dst1)
cv2.imshow('dst2',  dst2)
cv2.waitKey()    
cv2.destroyAllWindows()
